import { Concept, Question, MisconceptionItem, ActivityLog } from '../types';

export const CONCEPTS: Concept[] = [
  {
    id: 'thermo-01',
    name: 'Thermodynamics Foundations',
    subject: 'Chemistry',
    domain: 'Physical Chemistry',
    estimatedMastery: 92,
    confidenceScore: 94,
    status: 'strong',
    prerequisites: [],
    dependents: ['enthalpy-02', 'entropy-03'],
    totalResponses: 16,
    correctResponses: 15,
    incorrectResponses: 1,
    evidenceSummary: 'Sufficient consistent observations across state functions and first-law energy conservation.',
    isWeakVsInsufficient: 'mastered',
    recommendedAction: 'Mastery established. Revisit only for periodic decay maintenance.',
    position: { x: 355, y: 40 },
    level: 1,
  },
  {
    id: 'enthalpy-02',
    name: 'Enthalpy (ΔH)',
    subject: 'Chemistry',
    domain: 'Thermochemistry',
    estimatedMastery: 84,
    confidenceScore: 88,
    status: 'strong',
    prerequisites: ['thermo-01'],
    dependents: ['gibbs-04'],
    totalResponses: 14,
    correctResponses: 12,
    incorrectResponses: 2,
    evidenceSummary: 'Solid comprehension of Hess’s Law and endothermic/exothermic standard enthalpy changes.',
    isWeakVsInsufficient: 'mastered',
    recommendedAction: 'Ready to serve as verified foundational anchor for Gibbs derivations.',
    position: { x: 150, y: 190 },
    level: 2,
  },
  {
    id: 'entropy-03',
    name: 'Entropy (ΔS)',
    subject: 'Chemistry',
    domain: 'Statistical Thermodynamics',
    estimatedMastery: 76,
    confidenceScore: 82,
    status: 'developing',
    prerequisites: ['thermo-01'],
    dependents: ['gibbs-04'],
    totalResponses: 11,
    correctResponses: 8,
    incorrectResponses: 3,
    evidenceSummary: 'Demonstrated microstate intuition; minor variance on standard molar entropy temperature dependencies.',
    isWeakVsInsufficient: 'developing',
    recommendedAction: 'Solidifying; reinforce temperature coupling before downstream coupling.',
    position: { x: 560, y: 190 },
    level: 2,
  },
  {
    id: 'gibbs-04',
    name: 'Gibbs Energy (ΔG)',
    subject: 'Chemistry',
    domain: 'Equilibrium Thermodynamics',
    estimatedMastery: 41,
    confidenceScore: 63,
    status: 'uncertain',
    prerequisites: ['enthalpy-02', 'entropy-03'],
    dependents: ['cell-pot-05', 'eq-const-07'],
    totalResponses: 8,
    correctResponses: 5,
    incorrectResponses: 3,
    evidenceSummary: 'High posterior variance. High rate of hesitation and conflicting responses on non-standard spontaneity criteria.',
    isWeakVsInsufficient: 'developing',
    possibleMisconception: {
      title: 'ΔG° vs ΔG Spontaneity Criterion Misattribution',
      description: 'Tendency to assess instantaneous spontaneity using standard state ΔG° rather than reaction quotient-dependent ΔG.',
      confidence: 'Moderate',
      evidenceText: '2 of your last 3 responses suggest confusing ΔG° with instantaneous ΔG under non-equilibrium states.',
    },
    recommendedAction: 'High priority adaptive probe recommended to collapse posterior uncertainty.',
    position: { x: 355, y: 340 },
    level: 3,
  },
  {
    id: 'cell-pot-05',
    name: 'Cell Potential (E°cell)',
    subject: 'Chemistry',
    domain: 'Electrochemistry',
    estimatedMastery: 78,
    confidenceScore: 81,
    status: 'strong',
    prerequisites: ['gibbs-04'],
    dependents: ['electro-06', 'nernst-08'],
    totalResponses: 12,
    correctResponses: 9,
    incorrectResponses: 3,
    evidenceSummary: 'Accurate reduction potential lookups; occasionally neglects stoichiometric independence of intensive potential E°.',
    isWeakVsInsufficient: 'mastered',
    possibleMisconception: {
      title: 'Cell Potential and Gibbs Energy Conflation',
      description: 'You may be treating cell potential and Gibbs free energy as independent or inversely aligned quantities.',
      confidence: 'Moderate',
      evidenceText: '2 of your last 3 responses suggest treating ΔG° = -nFE°cell with sign confusion or stoichiometric multiplication errors.',
    },
    recommendedAction: 'Targeted probe to clarify sign relation ΔG° = -nFE°cell.',
    position: { x: 180, y: 490 },
    level: 4,
  },
  {
    id: 'eq-const-07',
    name: 'Equilibrium Constant (K)',
    subject: 'Chemistry',
    domain: 'Chemical Equilibria',
    estimatedMastery: 68,
    confidenceScore: 74,
    status: 'developing',
    prerequisites: ['gibbs-04'],
    dependents: ['nernst-08'],
    totalResponses: 9,
    correctResponses: 6,
    incorrectResponses: 3,
    evidenceSummary: 'Good understanding of Law of Mass Action; moderate difficulty linking ΔG° = -RT ln K.',
    isWeakVsInsufficient: 'developing',
    recommendedAction: '2 targeted calibration items required.',
    position: { x: 530, y: 490 },
    level: 4,
  },
  {
    id: 'electro-06',
    name: 'Electrochemistry Cells',
    subject: 'Chemistry',
    domain: 'Electrochemistry',
    estimatedMastery: 52,
    confidenceScore: 69,
    status: 'developing',
    prerequisites: ['cell-pot-05'],
    dependents: ['nernst-08'],
    totalResponses: 7,
    correctResponses: 4,
    incorrectResponses: 3,
    evidenceSummary: 'Galvanic vs electrolytic cell conventions demonstrated; salt bridge ion migration needs consolidation.',
    isWeakVsInsufficient: 'developing',
    recommendedAction: 'Integrate after Gibbs-Potential coupling is solidified.',
    position: { x: 80, y: 640 },
    level: 5,
  },
  {
    id: 'nernst-08',
    name: 'Nernst Equation',
    subject: 'Chemistry',
    domain: 'Non-Standard Electrochemistry',
    estimatedMastery: 28,
    confidenceScore: 78,
    status: 'weak',
    prerequisites: ['cell-pot-05', 'eq-const-07'],
    dependents: [],
    totalResponses: 10,
    correctResponses: 2,
    incorrectResponses: 8,
    evidenceSummary: 'Confirmed low ability estimate with high confidence (low standard error). Persistent sign inversion on reaction quotient Q term.',
    isWeakVsInsufficient: 'weak',
    possibleMisconception: {
      title: 'Reaction Quotient Q vs K in Nernst Potential',
      description: 'Frequently inverting Q numerator/denominator when calculating non-standard E under diluted electrolytic conditions.',
      confidence: 'Strong evidence',
      evidenceText: '4 consecutive incorrect attempts show logarithmic factor -0.0592/n log(Q) calculated with inverted product/reactant activities.',
    },
    recommendedAction: 'Prerequisite remediation required before testing full non-standard cell systems.',
    position: { x: 480, y: 640 },
    level: 5,
  },
  {
    id: 'faraday-09',
    name: 'Faraday’s Law & Electrolysis',
    subject: 'Chemistry',
    domain: 'Quantitative Electrochemistry',
    estimatedMastery: 50,
    confidenceScore: 21,
    status: 'insufficient_evidence',
    prerequisites: ['electro-06'],
    dependents: [],
    totalResponses: 1,
    correctResponses: 0,
    incorrectResponses: 1,
    evidenceSummary: 'Insufficient evidence. Only 1 diagnostic item administered. Posterior standard error σ(θ) exceeds reliability threshold.',
    isWeakVsInsufficient: 'insufficient',
    recommendedAction: 'Requires 3 exploratory diagnostic items to form initial ability estimate.',
    position: { x: 80, y: 790 },
    level: 6,
  }
];

export const QUESTIONS_POOL: Question[] = [
  {
    id: 'q-gibbs-cell-01',
    conceptId: 'gibbs-04',
    conceptName: 'Gibbs Energy',
    subject: 'Electrochemistry & Thermodynamics',
    stem: 'Based on the following standard galvanic cell notation and standard reduction potentials at 298 K:\n\nZn(s) | Zn²⁺(aq, 1.0 M) || Cu²⁺(aq, 1.0 M) | Cu(s)\n\nGiven E°(Zn²⁺/Zn) = -0.76 V and E°(Cu²⁺/Cu) = +0.34 V, what is the standard Gibbs free energy change (ΔG°) for the spontaneous cell reaction, and what does its sign imply?',
    contextNotation: 'Zn(s) | Zn²⁺(1.0 M) || Cu²⁺(1.0 M) | Cu(s)  •  F ≈ 96,485 C/mol  •  n = 2',
    options: [
      {
        id: 'opt-a',
        label: 'A',
        text: 'ΔG° = -212.3 kJ/mol; negative sign indicates the cell reaction is thermodynamically spontaneous under standard conditions.',
      },
      {
        id: 'opt-b',
        label: 'B',
        text: 'ΔG° = +212.3 kJ/mol; positive sign indicates work is done by the system on the surroundings during spontaneous discharge.',
        isMisconceptionDistractor: true,
        misconceptionRationale: 'Cell potential and Gibbs free energy may be getting conflated. ΔG° is inversely related to E°cell via ΔG° = -nFE°cell.',
      },
      {
        id: 'opt-c',
        label: 'C',
        text: 'ΔG° = -106.1 kJ/mol; because standard potentials are intensive, n is omitted from the energetic conversion.',
        isMisconceptionDistractor: true,
        misconceptionRationale: 'Omission of n indicates confusion between intensive potential (Volts = J/C) and extensive thermodynamic free energy (Joules).',
      },
      {
        id: 'opt-d',
        label: 'D',
        text: 'ΔG° = 0 kJ/mol; standard cell notation implies the system is at dynamic equilibrium at 1.0 M concentrations.',
        isMisconceptionDistractor: true,
        misconceptionRationale: 'Equilibrium corresponds to non-standard E = 0 and ΔG = 0, not standard conditions where Q = 1.',
      }
    ],
    correctOptionId: 'opt-a',
    explanation: 'For the standard cell reaction Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s), the standard cell potential is E°cell = E°(cathode) - E°(anode) = +0.34 V - (-0.76 V) = +1.10 V. The relationship to standard Gibbs free energy is ΔG° = -nFE°cell. With n = 2 mol e⁻, ΔG° = -2 × 96,485 C/mol × 1.10 J/C = -212,267 J/mol ≈ -212.3 kJ/mol. A negative ΔG° confirms thermodynamic spontaneity.',
    diagnosticRationale: {
      uncertaintyReason: 'Your current estimate for Gibbs Energy is uncertain (confidence: 63%, posterior variance elevated).',
      recentDifficultyReason: 'You recently showed difficulty connecting thermodynamic state functions to electrochemical work.',
      prerequisiteReason: 'Gibbs Energy is a direct prerequisite for the downstream concept Cell Potential (E°cell) being studied.',
      informationGainReason: 'This item maximizes Fisher Information I(θ = -0.22) = 1.48, providing maximum diagnostic discrimination.',
      fisherInformation: 1.48,
      estimatedTheta: -0.22,
      standardError: 0.38,
      itemDiscrimination: 1.82,
      itemDifficulty: -0.15,
      prerequisiteCoverageIndex: 0.89,
      utilityScore: 0.94,
    }
  },
  {
    id: 'q-nernst-02',
    conceptId: 'nernst-08',
    conceptName: 'Nernst Equation',
    subject: 'Physical Chemistry',
    stem: 'Consider a concentration cell operated at 298 K with copper electrodes: Cu(s) | Cu²⁺(aq, 0.0010 M) || Cu²⁺(aq, 1.0 M) | Cu(s). How does the cell potential change as the reaction approaches equilibrium?',
    contextNotation: 'E = E° - (0.0592 / n) log(Q)  •  E° = 0.00 V for identical half-cells',
    options: [
      {
        id: 'opt-a',
        label: 'A',
        text: 'Initial E is positive (+0.089 V) and decreases continuously toward 0.00 V as Cu²⁺ concentrations equalize.',
      },
      {
        id: 'opt-b',
        label: 'B',
        text: 'Initial E is 0.00 V because identical chemical species have zero net electrochemical driving force.',
        isMisconceptionDistractor: true,
        misconceptionRationale: 'Confusing standard potential E° (which is 0) with non-standard potential E driven by the entropic gradient of concentration.',
      },
      {
        id: 'opt-c',
        label: 'C',
        text: 'Initial E is negative (-0.089 V) because the anode compartment has lower ionic activity than standard state.',
        isMisconceptionDistractor: true,
        misconceptionRationale: 'Inversion of the reaction quotient Q = [Cu²⁺_dilute] / [Cu²⁺_conc] in the Nernst logarithm.',
      },
      {
        id: 'opt-d',
        label: 'D',
        text: 'Initial E remains invariant until the copper anode electrode is completely dissolved.',
        isMisconceptionDistractor: true,
      }
    ],
    correctOptionId: 'opt-a',
    explanation: 'In a concentration cell, E° = 0. The anode reaction generates Cu²⁺ in the dilute compartment (0.001 M), and cathode plates out Cu²⁺ from the concentrated compartment (1.0 M). Q = [Cu²⁺_dilute] / [Cu²⁺_conc] = 10⁻³. E = 0 - (0.0592/2) log(10⁻³) = -0.0296 × (-3) = +0.0888 V. As current flows, Q increases to 1, causing E to approach 0 V at equilibrium.',
    diagnosticRationale: {
      uncertaintyReason: 'Identifies whether low performance on Nernst is caused by Q inversion vs lack of conceptual grasp.',
      recentDifficultyReason: 'Confirmed low ability estimate (28% mastery) requires targeted diagnostic isolation.',
      prerequisiteReason: 'Tests mastery of reaction quotient integration with cell potential.',
      informationGainReason: 'High discriminatory power (a = 2.1) between sign inversion misconceptions and conceptual gaps.',
      fisherInformation: 1.62,
      estimatedTheta: -0.85,
      standardError: 0.29,
      itemDiscrimination: 2.10,
      itemDifficulty: -0.70,
      prerequisiteCoverageIndex: 0.95,
      utilityScore: 0.91,
    }
  }
];

export const MISCONCEPTIONS: MisconceptionItem[] = [
  {
    id: 'misc-01',
    conceptId: 'cell-pot-05',
    conceptName: 'Cell Potential (E°cell)',
    title: 'Cell Potential and Gibbs Free Energy Conflation',
    statement: 'You may be treating cell potential and Gibbs free energy as independent quantities rather than recognizing their inverse thermodynamic coupling.',
    evidence: '2 of your last 3 responses suggest this pattern.',
    confidence: 'Moderate',
    recommendedAction: 'Review the relationship ΔG° = -nFE°cell with sign invariance exercises.',
    targetedQuestionsCount: 3,
    affectedPrerequisites: ['gibbs-04', 'cell-pot-05'],
  },
  {
    id: 'misc-02',
    conceptId: 'gibbs-04',
    conceptName: 'Gibbs Energy (ΔG)',
    title: 'Standard ΔG° vs Instantaneous ΔG Spontaneity Criterion',
    statement: 'Using standard state ΔG° rather than instantaneous ΔG (or Q vs K) to determine whether a non-standard reaction proceeds spontaneously.',
    evidence: '3 recent attempts applied ΔG° < 0 as the absolute criterion under varying concentration stresses.',
    confidence: 'Emerging pattern',
    recommendedAction: 'Practice non-standard spontaneity drills contrasting standard potential with current state driving forces.',
    targetedQuestionsCount: 3,
    affectedPrerequisites: ['enthalpy-02', 'entropy-03'],
  },
  {
    id: 'misc-03',
    conceptId: 'nernst-08',
    conceptName: 'Nernst Equation',
    title: 'Reaction Quotient Q Activity Inversion',
    statement: 'Frequently inverting the ratio of ionic activities [Products]/[Reactants] in the logarithmic term of the Nernst equation.',
    evidence: '4 consecutive incorrect attempts calculated non-standard cell potential with inverted signs for diluted electrolytes.',
    confidence: 'Strong evidence',
    recommendedAction: 'Dedicated 3-item targeted drill on cell quotient setup and oxidation/reduction half-cell identification.',
    targetedQuestionsCount: 3,
    affectedPrerequisites: ['cell-pot-05', 'eq-const-07'],
  }
];

export const RECENT_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    timestamp: '14 min ago',
    type: 'adaptive_probe',
    title: 'Administered Adaptive Probe',
    description: 'Diagnosed Gibbs Free Energy & Cell Potential coupling with item discrimination a = 1.82.',
    conceptName: 'Gibbs Energy',
    deltaMetric: 'Uncertainty reduced: σ(θ) 0.52 → 0.38',
    statusBadge: 'uncertain',
  },
  {
    id: 'act-2',
    timestamp: '2 hours ago',
    type: 'misconception_flag',
    title: 'Possible Misconception Flagged',
    description: 'Pattern identified: E°cell and ΔG° sign coupling conflict detected with moderate confidence.',
    conceptName: 'Cell Potential',
    statusBadge: 'developing',
  },
  {
    id: 'act-3',
    timestamp: 'Yesterday',
    type: 'mastery_promotion',
    title: 'Prerequisite Validated',
    description: 'Enthalpy (ΔH) verified with high statistical reliability across 14 independent test items.',
    conceptName: 'Enthalpy (ΔH)',
    deltaMetric: 'Mastery: 72% → 84%',
    statusBadge: 'strong',
  },
  {
    id: 'act-4',
    timestamp: '2 days ago',
    type: 'diagnostic_update',
    title: 'Insufficient Evidence Flagged',
    description: 'Faraday’s Law observed with only 1 item. Model withheld mastery score to prevent premature low score label.',
    conceptName: 'Faraday’s Law',
    deltaMetric: 'Status: Insufficient Evidence',
    statusBadge: 'insufficient_evidence',
  }
];
